### PR TITLE
Add support for official Django versions and drop EOL Python & Django

### PR DESCRIPTION
**Pull request by irtazaakram**
Hi

I've made this PR that

- add support for Django 4.1 & 4.2
- drop support for Python 2.7, 3.5, 3.6, 3.7(EOL https://devguide.python.org/versions/#unsupported-versions)
- drop support for Django 1.11, 2.2, 3.0, 3.1(EOL https://www.djangoproject.com/download/#unsupported-versions)

can we also have a new release after this PR is merged?

Thanks,

### CODE REVIEW

**Comment by sergei-maertens** [comment]
Thank you! I should be able to release a new version today. I have been meaning to add docs on how to replace this library with Django's built in choices too. Can I ask what your use case is still, now that django has them built in? What features are you using that Django doesn't have?

**Comment by irtazaakram** [comment]
Hi @sergei-maertens,

Thank you for quick response on this PR. This update is related to ongoing effort to update Django to 4.2 on openedx.
Django-choices is extensively used mainly in the [course-discovery](https://github.com/openedx/course-discovery/blob/master/course_discovery/apps/course_metadata/choices.py) & [taxonomy-connector](https://github.com/openedx/taxonomy-connector/blob/master/taxonomy/choices.py).

Thanks,

**Comment by sergei-maertens** [comment]
@irtazaakram thank you for the quick feedback too! That looks like some pretty straight-forward usage - are you making use of `DjangoChoices.values` / `DjangoChoices.labels` / `DjangoChoices.get_choice` and the likes? If not, I think it should be fairly straight forward to add a helper to the library to generate the equivalent Django's `models.TextChoices` and family from the definitions so you could pretty much copy and paste the replacements.

**Review by sergei-maertens — APPROVED** [review]

**Comment by irtazaakram** [comment]
Thank you for the insights @sergei-maertens. I will share the PR to replace Django-choices with builtins for both repos with you.

& Thank you for merging this PR 🎉

**Comment by sergei-maertens** [comment]
@irtazaakram I think I phrased it badly - I plan to work on and release version 2.0 in the next few hours, which will include a management command to generate the code to convert to native Django choices. That should help existing projects migrate away from the django-choices library. It'd will probably save you a bunch of manual labor so I'd recommend waiting for that.

**Comment by irtazaakram** [comment]
oh ok .. Thanks @sergei-maertens. I'll wait for that then.

**Comment by sergei-maertens** [comment]
@irtazaakram it is done - version 2.0.0 is now on PyPI and the documentation on how to migrate can be found here: https://django-choices.readthedocs.io/en/latest/migrating.html

**Comment by irtazaakram** [comment]
Thank you @sergei-maertens 🎉

**Pull request merged**
