### PR TITLE
Fixed bug, when the `Chocies.validator` was producing the wrong output.

### LINKED ISSUE #35: Invalid exception formatting within Chocies.validator
I'm' sorry to spam you with issues like that :^) I noticed a small bug in Choices.validator, you don't pass the value to exception:

```
python3.4/site-packages/djchoices/choices.py in __call__(self, value)
    118     def __call__(self, value):
    119         if value not in self.values:
--> 120             raise ValidationError('Select a valid choice. %(value)s is not '
    121                                   'one of the available choices.')
    122 

ValidationError: ['Select a valid choice. %(value)s is not one of the available choices.']
```

### PR DESCRIPTION
**Pull request by sobolevn**
Just a small fix with passing the value into formating.
Closes #35, refs: https://github.com/bigjason/django-choices/pull/37

Also, I have added a test case for the fix.

P.S.
You need a `CONTRIBUTING.md` file to specify branches to create PR to and so on.

### CODE REVIEW

**Comment by sobolevn** [comment]
There's also something wrong with coverage.

**Comment by sergei-maertens** [comment]
Thanks, yeah, I need to get into those templates asap. I'll have a look at
the coverage reporting tomorrow.

**Comment by sobolevn** [comment]
Fixed the test, now it is passing.

**Comment by sergei-maertens** [comment]
:+1:
I will make a PyPI release in a few minutes

**Pull request merged**
