### PR TITLE
Adding django3 testing in tox matrix.

### PR DESCRIPTION
**Pull request by awais786**
Using this package extensively. So it would be helpful if new version release with django3.2 support.

Tests are not running.
**Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.**

### CODE REVIEW

**Comment by awais786** [comment]
@sergei-maertens Please review.

**Comment by sergei-maertens** [comment]
Sorry for the quiet and thanks for the contributions! Hopefully I can take
a look this weekend :-)

**Comment by sergei-maertens** [comment]
@awais786 thanks for the contribution! was very busy and this constantly fell of the radar. I'll migrate to Github actions in the next couple of hours, and will include your changes to the build matrix.

**Comment by sergei-maertens** [comment]
@awais786 I'm going to close this PR since I've included the content in the Github Actions migration. Feel free to add yourself to `CONTRIBUTORS.md` though, as you provided valuable input!

**Pull request closed without merging**
